repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.0
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      # Run the linter.
      - id: ruff
        files: src/
      # Run the formatter.
      - id: ruff-format
        files: "src/"
    
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        files: "src/"